baseURL = 'https://newbelog.netlify.app/'
languageCode = 'id-id'
title = 'Blogku'
theme = 'PaperMod'

[params]
    env = "production"
    description = "Berbagi inspirasi dan tutorial"
    author = "admin"
    defaultTheme = "auto" # Otomatis Dark Mode sesuai HP user
    assets = { disableHLJS = true }
    ShowReadingTime = true
    ShowShareButtons = true
    displayFullLangName = true
    ShowPostNavLinks = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Semua Artikel"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "admin"
    name = "Admin Panel"
    url = "/admin/"
    weight = 20
  [[menu.main]]
    identifier = "login"
    name = "Login / Daftar"
    url = "#" # Ini akan memicu pop-up Netlify Identity
    weight = 30
    pre = "<span onclick='netlifyIdentity.open()'>" # Trik agar tombol ini memicu login
    post = "</span>"