baseURL = 'https://newbelog.netlify.app/'
languageCode = 'id-id'
title = 'Blogku'
theme = 'PaperMod'

[params]
    env = "production"
    description = "Berbagi inspirasi dan tutorial"
    author = "admin"
    defaultTheme = "auto" # Otomatis Dark Mode sesuai HP user
    assets = { disableHLJS = true }
    ShowReadingTime = true
    ShowShareButtons = true
    displayFullLangName = true
    ShowPostNavLinks = true
    comments = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Semua Artikel"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "admin"
    name = "Admin Panel"
    url = "/admin/"
    weight = 20

  [[menu.main]]
    identifier = "login-btn"
    name = "Login / Daftar"
    url = "#"
    weight = 20
    pre = "<span id='menu-login' onclick='netlifyIdentity.open()'>"
    post = "</span>"

  [[menu.main]]
    identifier = "logout-btn"
    name = "Logout"
    url = "#"
    weight = 30
    pre = "<span id='menu-logout' onclick='netlifyIdentity.logout()' style='display:none; color:red;'>"
    post = "</span>"