backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Tulis Artikel Baru"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Deskripsi Singkat", name: "description", widget: "text"}
      - {label: "Gambar Sampul", name: "image", widget: "image", required: false}
      - {label: "Isi Blog", name: "body", widget: "markdown"}